project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-EE397TN9ZL" 
  cookie-consent: true
  title: "R Club for Public Health and Social Work"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - plan.qmd
      - href: code_of_conduct.qmd
      - us.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

