---
title: "Session Plan"
---

These sessions serve as a roadmap, offering a glimpse into the topics we believe are essential for our club. Please note, this itinerary **is not set in stone**; we aim for *flexibility* rather than *adherence to a strict sequence*. Our goal is to adapt the content and order of sessions based on the group's progress, interests, and feedback.


## Session 1: Introduction to R, RStudio, and Package Management

`April 26, 2024 at 10:30 am via Zoom`

### Objective
Familiarize participants with the R environment, RStudio interface, and the basics of package management.

### Topics
- Overview of R and its importance in data analysis.
- Installing R and RStudio; navigating the RStudio interface.
- Working in projects
- Basic R syntax: variables, data types, and simple operations.
- Understanding R packages, installing and loading them using `install.packages()` and `library()`.
- Exploring package documentation.

### Activity
Install R and RStudio, execute basic R commands, install a package (e.g., `tidyverse`), and explore its documentation.

## Session 2: Data Manipulation with Tidyverse

### Objective
Introduce the Tidyverse suite for data manipulation and visualization, focusing on `dplyr`,  including reshaping data with `pivot_longer()` and `pivot_wider()`.

### Topics
- Brief overview of the Tidyverse packages.
- Data manipulation with `dplyr` (filtering, selecting, mutating, summarizing, and grouping).
- Reshaping data with `pivot_longer()` and `pivot_wider()`.

### Activity
Participants will use `dplyr` to manipulate a dataset, and practice reshaping data.

## Session 3: Introduction to Reproducible Reports with R Markdown and Quarto

### Objective: 
Introduce the concept of reproducible research and reports using R Markdown and Quarto.

### Topics:
- What is R Markdown and Quarto?
- Creating a simple report integrating R code and narrative text.
- Exporting reports to different formats (HTML, PDF, Word).

### Activity
Create a basic R Markdown document that includes text, code, and outputs.


## Session 4: Data Visualization with ggplot2 and Creating Tables

### Objective
Expand on basic ggplot2 usage and introduce methods for creating well-formatted tables for reports.

### Topics
- Advanced data visualization techniques with `ggplot2`.
- Customizing plots to improve readability and aesthetics.
- Creating tables with `gtsummary`, and`gt`  

### Activity
Create a visualization that tells a story about a dataset. Generate a report including a well-formatted table.

## Session 5: Version Control with GitHub

### Objective
Introduce the concept of version control and how to use GitHub for project management and collaboration.

### Topics:
- Basics of version control and why it's important.
- Setting up a GitHub account and understanding the GitHub interface.
- Creating repositories, committing changes, and understanding the workflow (clone, add, commit, push).
- Collaborating on projects (forks, branches, pull requests).

### Activity:

Create a new repository on GitHub and practice making commits and pushing changes.

## Session 6: Creating Websites with Quarto

### Objective:
Teach participants how to create and publish websites using Quarto, an open-source scientific and technical publishing system built on Pandoc.

### Topics:
- Creating static websites with Quarto and customizing the layout and appearance.
- Publishing a Quarto website on GitHub Pages.

### Activity: 
Participants will create a simple website using Quarto that includes text, code outputs, and visualizations, and then publish it on GitHub Pages.




